config/routes.rb
GalleryJqueryFileUpload::Application.routes.draw do

  resources :galleries 
  resources :pictures

  root :to => 'galleries#index'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base

  has_many :pictures, :dependent => :destroy
end

app/models/picture.rb
class Picture < ActiveRecord::Base

  belongs_to :gallery

  has_attached_file :image,
    :path => ":rails_root/public/images/:id/:filename",
    :url  => "/images/:id/:filename"

  do_not_validate_attachment_file_type :image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery  = Gallery.find(params[:id])
    @pictures = @gallery.pictures

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save

        if params[:images]
          # The magic is here ;)
          params[:images].each { |image|
            @gallery.pictures.create(image: image)
          }
        end

        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(gallery_params)
        if params[:images]
          # The magic is here ;)
          params[:images].each { |image|
            @gallery.pictures.create(image: image)
          }
        end
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end

  private

  def gallery_params
    params.require(:gallery).permit(:description,
                                    :name,
                                    :pictures
                                   )
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  # GET /pictures
  # GET /pictures.json
  def index

    @gallery = Gallery.find(params[:gallery_id])

    @pictures = @gallery.pictures

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @gallery = Gallery.find(params[:gallery_id])
    @picture = @gallery.pictures.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    #@gallery = Gallery.find(params[:gallery_id])

    @picture = Picture.find(params[:id])
    # @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])

    if @picture.save
      respond_to do |format|
        format.html {
          render :json => [@picture.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json {
          render :json => [@picture.to_jq_upload].to_json
        }
      end
    else
      render :json => [{:error => "custom_failure"}], :status => 304
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update

    @gallery = Gallery.find(params[:gallery_id])

    @picture = @gallery.pictures.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(picture_params)
        format.html { redirect_to gallery_path(@gallery), notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    #@gallery = Gallery.find(params[:gallery_id])
    #@picture = @gallery.pictures.find(params[:id])
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def make_default
    @picture = Picture.find(params[:id])
    @gallery = Gallery.find(params[:gallery_id])

    @gallery.cover = @picture.id
    @gallery.save

    respond_to do |format|
      format.js
    end
  end

  private

  def picture_params
    params.require(:picture).permit(:description, :gallery_id, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/galleries/_form.html.erb
<%= form_for @gallery, :html => { :class => 'form-horizontal', multipart: true } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :pictures, :class => 'control-label' %>
    <div class="controls">
      <!-- The magic is coming ...look at my eyes....shazammmm -->
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                galleries_path, :class => 'btn btn-mini' %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<%- model_class = @gallery.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/galleries/index.html.erb
<div class="row">
  <h1>Galleries</h1>
  <%= link_to 'New', new_gallery_path, :class => 'btn btn-mini' %>
  <p></p>
  <tr class="thumbnails files">
    <% @galleries.each do |gallery| %>
        <li class="span4" id="gallery_<%= gallery.id %>">
          <div class="thumbnail">
            <% if gallery.pictures.first %>
            <%= link_to image_tag(gallery.pictures.first.image.url), gallery_path(gallery) %>
            <% else %>
              N/A
            <% end %>
            <div class="caption">
              <p style="text-align: center;">
                <%= gallery.name.truncate(14) %>
                <%= link_to "Show", gallery_path(gallery) %>
                <%= link_to "Edit", edit_gallery_path(gallery) %>
                <%= link_to "Delete", gallery,
                  :data => { :confirm => "Are you sure?" },
                  :method => :delete
                %>
              </p>
            </div>
          </div>
        </li>
    <% end %>
  </tr>

</div>

app/views/galleries/new.html.erb
<%- model_class = @gallery.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/galleries/show.html.erb
<div class="row">
  <h1>Gallery</h1>

  <input type="hidden" id="galleryID" value="<%= @gallery.id %>">

  <p>
    <b>Name: </b>
    <%= @gallery.name %>
  </p>

  <p>
    <b>Description: </b>
    <%= @gallery.description %>
  </p>

  <div class="form-actions">
    <%= link_to 'Back', galleries_path, :class => 'btn btn-mini'  %>
    <%= link_to 'Edit gallery', edit_gallery_path(@gallery), :class => 'btn btn-mini' %>
    <%= link_to 'Delete gallery', gallery_path(@gallery), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-mini' %>
  </div>

<h2>Pictures</h2>
</div>

<div class="row">
  <ul class="thumbnails files">
<% unless @pictures.empty? %>
  <% @pictures.each do |pic| %>
    <li class="span3" id="picture_<%= pic.id %>">
    <div class="thumbnail">
      <%= image_tag pic.image.url %>
      <div class="caption">
        <p style="text-align: center;">
        <%= link_to "Edit picture", picture_path(pic) %>

        <%=
          link_to "Delete picture", pic,
            :data => { :confirm => "Are you sure?" },
            :method => :delete
          %>

        </p>
      </div>
    </div>
    </li>
  <% end %>
<% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GalleryJqueryFileUpload</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="span8"><%= link_to "Home", root_path %></div>
  </div>
  <div class="row">
    <div class="span8"><%= yield %></div>
  </div>
</div>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for [@gallery, @picture], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  
    <%= image_tag @picture.image.large.url, :id => 'cropbox' %>
  
  <% %w[x y w h].each do |attribute| %>
    <%= f.hidden_field "crop_#{attribute}" %>
  <% end %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary  btn-mini' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                gallery_path(@gallery), :class => 'btn btn-mini' %>
    <%= link_to 'Default', '', :class => 'btn btn-mini btn-success' , :id => 'make_default'%>

  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
    $(function () {
      $('#make_default').click(function(event) {
        event.preventDefault();
        $.ajax({
          url: '<%= make_default_gallery_pictures_path %>',
          type: 'POST',
          data: {id : <%= @picture.id %>, gallery_id : <%= @gallery.id %>}
        });
      });
    });
</script>

app/views/pictures/destroy.js.erb
$('#picture_<%= @picture.id %>').fadeOut();

app/views/pictures/edit.html.erb
<div class="page-header">
  <h1>Edit Picture</h1>
</div>
<%= render :partial => 'form' %>

app/views/pictures/index.html.erb
<%- model_class = Picture.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:gallery_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= link_to picture.id, picture_path(picture) %></td>
        <td><%= picture.description %></td>
        <td><%= picture.image %></td>
        <td><%= picture.gallery_id %></td>
        <td><%=l picture.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_picture_path(picture), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      picture_path(picture),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_picture_path,
            :class => 'btn btn-primary' %>

app/views/pictures/make_default.js.erb
$('<span style="color: #46a546; margin-left: 15px; font-weight: bold;">Done!</span>').insertAfter('#make_default').delay(3000).fadeOut('slow');

app/views/pictures/new.html.erb
<%- model_class = @picture.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pictures/show.html.erb
<%- model_class = @picture.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @picture.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @picture.image %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gallery_id) %>:</strong></dt>
  <dd><%= @picture.gallery_id %></dd>
</dl>
 
<p>
  <strong>picture:</strong>
  <%= image_tag @picture.image.url(:large) %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              gallery_path(@picture.gallery_id), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_picture_path(@picture), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              picture_path(@picture),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>